### ISSUE TITLE
Themes Bug

### ISSUE THREAD

**Issue by Zth0rM** [Maxie01/we-made-a-theme#14]
![discordbug1](https://user-images.githubusercontent.com/29271033/26915179-39575202-4c4f-11e7-8c99-37b2275f1ede.PNG)
![discordbug2](https://user-images.githubusercontent.com/29271033/26915184-4250eaa8-4c4f-11e7-938e-7582a2950aa7.PNG)
Is this a bug or just a problem with my discord? Because I've had tried to uninstall both discord and better discord and it doesn't do much. Like every month, something will change. Can someone help?

**Comment by Pierce01** [comment]
Sadly, i don't work on these themes. Tell the theme devs to add this to their code
```css
div[class*="container-"], div[class*="content-"]:not([class="content-region"]) {
    background-color: rgba(0,0,0,0) !important;
}
```
