### ISSUE TITLE
Hotfix areas

### ISSUE THREAD

**Issue by Pierce01** [Maxie01/we-made-a-theme#19]
i need to redo all the hotfixs.... current code is aids

```css
div[class*="channels-"], div[class*="container-"], div.titleWrapper-3Vi_wz.theme-dark > div {
	background-color: rgba(0,0,0,.3) !important;
}

div.titleWrapper-3Vi_wz.theme-dark > div {
	background-color: rgba(0,0,0,.6) !important;
}

form {
	background-color: transparent !important;
}
```
